// ── 30 terminal colorschemes ───────────────────────────────
// Each theme maps directly to xterm.js ITheme interface.
// background also drives the #crt background via applyTheme().

export const themes = {
    // ── Dark themes ──────────────────────────────────────────

    'catppuccin-mocha': {
        _label: 'Catppuccin Mocha',
        background: '#1e1e2e',
        foreground: '#cdd6f4',
        cursor: '#f5e0dc',
        black: '#181825',
        red: '#f38ba8',
        green: '#a6e3a1',
        yellow: '#f9e2af',
        blue: '#89b4fa',
        magenta: '#cba6f7',
        cyan: '#89dceb',
        white: '#cdd6f4',
        brightBlack: '#45475a',
        brightRed: '#f38ba8',
        brightGreen: '#a6e3a1',
        brightYellow: '#f9e2af',
        brightBlue: '#89b4fa',
        brightMagenta: '#cba6f7',
        brightCyan: '#89dceb',
        brightWhite: '#cdd6f4',
    },

    'catppuccin-macchiato': {
        _label: 'Catppuccin Macchiato',
        background: '#24273a',
        foreground: '#cad3f5',
        cursor: '#f4dbd6',
        black: '#1e2030',
        red: '#ed8796',
        green: '#a6da95',
        yellow: '#eed49f',
        blue: '#8aadf4',
        magenta: '#c6a0f6',
        cyan: '#8bd5ca',
        white: '#cad3f5',
        brightBlack: '#494d64',
        brightRed: '#ed8796',
        brightGreen: '#a6da95',
        brightYellow: '#eed49f',
        brightBlue: '#8aadf4',
        brightMagenta: '#c6a0f6',
        brightCyan: '#8bd5ca',
        brightWhite: '#cad3f5',
    },

    'catppuccin-latte': {
        _label: 'Catppuccin Latte',
        background: '#eff1f5',
        foreground: '#4c4f69',
        cursor: '#dc8a78',
        black: '#5c5f77',
        red: '#d20f39',
        green: '#40a02b',
        yellow: '#df8e1d',
        blue: '#1e66f5',
        magenta: '#8839ef',
        cyan: '#179299',
        white: '#acb0be',
        brightBlack: '#6c6f85',
        brightRed: '#d20f39',
        brightGreen: '#40a02b',
        brightYellow: '#df8e1d',
        brightBlue: '#1e66f5',
        brightMagenta: '#8839ef',
        brightCyan: '#179299',
        brightWhite: '#bcc0cc',
    },

    'tokyonight-storm': {
        _label: 'Tokyo Night Storm',
        background: '#24283b',
        foreground: '#c0caf5',
        cursor: '#c0caf5',
        black: '#1d202f',
        red: '#f7768e',
        green: '#9ece6a',
        yellow: '#e0af68',
        blue: '#7aa2f7',
        magenta: '#bb9af7',
        cyan: '#7dcfff',
        white: '#a9b1d6',
        brightBlack: '#414868',
        brightRed: '#f7768e',
        brightGreen: '#9ece6a',
        brightYellow: '#e0af68',
        brightBlue: '#7aa2f7',
        brightMagenta: '#bb9af7',
        brightCyan: '#7dcfff',
        brightWhite: '#c0caf5',
    },

    'tokyonight-night': {
        _label: 'Tokyo Night',
        background: '#1a1b26',
        foreground: '#c0caf5',
        cursor: '#c0caf5',
        black: '#15161e',
        red: '#f7768e',
        green: '#9ece6a',
        yellow: '#e0af68',
        blue: '#7aa2f7',
        magenta: '#bb9af7',
        cyan: '#7dcfff',
        white: '#a9b1d6',
        brightBlack: '#414868',
        brightRed: '#f7768e',
        brightGreen: '#9ece6a',
        brightYellow: '#e0af68',
        brightBlue: '#7aa2f7',
        brightMagenta: '#bb9af7',
        brightCyan: '#7dcfff',
        brightWhite: '#c0caf5',
    },

    'dracula': {
        _label: 'Dracula',
        background: '#282a36',
        foreground: '#f8f8f2',
        cursor: '#f8f8f2',
        black: '#21222c',
        red: '#ff5555',
        green: '#50fa7b',
        yellow: '#f1fa8c',
        blue: '#bd93f9',
        magenta: '#ff79c6',
        cyan: '#8be9fd',
        white: '#f8f8f2',
        brightBlack: '#6272a4',
        brightRed: '#ff6e6e',
        brightGreen: '#69ff94',
        brightYellow: '#ffffa5',
        brightBlue: '#d6acff',
        brightMagenta: '#ff92df',
        brightCyan: '#a4ffff',
        brightWhite: '#ffffff',
    },

    'gruvbox-dark': {
        _label: 'Gruvbox Dark',
        background: '#282828',
        foreground: '#ebdbb2',
        cursor: '#ebdbb2',
        black: '#282828',
        red: '#cc241d',
        green: '#98971a',
        yellow: '#d79921',
        blue: '#458588',
        magenta: '#b16286',
        cyan: '#689d6a',
        white: '#a89984',
        brightBlack: '#928374',
        brightRed: '#fb4934',
        brightGreen: '#b8bb26',
        brightYellow: '#fabd2f',
        brightBlue: '#83a598',
        brightMagenta: '#d3869b',
        brightCyan: '#8ec07c',
        brightWhite: '#ebdbb2',
    },

    'gruvbox-material': {
        _label: 'Gruvbox Material',
        background: '#1d2021',
        foreground: '#d4be98',
        cursor: '#d4be98',
        black: '#32302f',
        red: '#ea6962',
        green: '#a9b665',
        yellow: '#d8a657',
        blue: '#7daea3',
        magenta: '#d3869b',
        cyan: '#89b482',
        white: '#d4be98',
        brightBlack: '#504945',
        brightRed: '#ea6962',
        brightGreen: '#a9b665',
        brightYellow: '#d8a657',
        brightBlue: '#7daea3',
        brightMagenta: '#d3869b',
        brightCyan: '#89b482',
        brightWhite: '#d4be98',
    },

    'nord': {
        _label: 'Nord',
        background: '#2e3440',
        foreground: '#d8dee9',
        cursor: '#d8dee9',
        black: '#3b4252',
        red: '#bf616a',
        green: '#a3be8c',
        yellow: '#ebcb8b',
        blue: '#81a1c1',
        magenta: '#b48ead',
        cyan: '#88c0d0',
        white: '#e5e9f0',
        brightBlack: '#4c566a',
        brightRed: '#bf616a',
        brightGreen: '#a3be8c',
        brightYellow: '#ebcb8b',
        brightBlue: '#81a1c1',
        brightMagenta: '#b48ead',
        brightCyan: '#8fbcbb',
        brightWhite: '#eceff4',
    },

    'onedark': {
        _label: 'One Dark',
        background: '#282c34',
        foreground: '#abb2bf',
        cursor: '#528bff',
        black: '#3f4451',
        red: '#e06c75',
        green: '#98c379',
        yellow: '#e5c07b',
        blue: '#61afef',
        magenta: '#c678dd',
        cyan: '#56b6c2',
        white: '#abb2bf',
        brightBlack: '#4f5666',
        brightRed: '#e06c75',
        brightGreen: '#98c379',
        brightYellow: '#e5c07b',
        brightBlue: '#61afef',
        brightMagenta: '#c678dd',
        brightCyan: '#56b6c2',
        brightWhite: '#ffffff',
    },

    'solarized-dark': {
        _label: 'Solarized Dark',
        background: '#002b36',
        foreground: '#839496',
        cursor: '#839496',
        black: '#073642',
        red: '#dc322f',
        green: '#859900',
        yellow: '#b58900',
        blue: '#268bd2',
        magenta: '#d33682',
        cyan: '#2aa198',
        white: '#eee8d5',
        brightBlack: '#002b36',
        brightRed: '#cb4b16',
        brightGreen: '#586e75',
        brightYellow: '#657b83',
        brightBlue: '#839496',
        brightMagenta: '#6c71c4',
        brightCyan: '#93a1a1',
        brightWhite: '#fdf6e3',
    },

    'monokai': {
        _label: 'Monokai',
        background: '#272822',
        foreground: '#f8f8f2',
        cursor: '#f8f8f0',
        black: '#272822',
        red: '#f92672',
        green: '#a6e22e',
        yellow: '#f4bf75',
        blue: '#66d9e8',
        magenta: '#ae81ff',
        cyan: '#a1efe4',
        white: '#f8f8f2',
        brightBlack: '#75715e',
        brightRed: '#f92672',
        brightGreen: '#a6e22e',
        brightYellow: '#f4bf75',
        brightBlue: '#66d9e8',
        brightMagenta: '#ae81ff',
        brightCyan: '#a1efe4',
        brightWhite: '#f9f8f5',
    },

    'rose-pine': {
        _label: 'Rosé Pine',
        background: '#191724',
        foreground: '#e0def4',
        cursor: '#524f67',
        black: '#26233a',
        red: '#eb6f92',
        green: '#31748f',
        yellow: '#f6c177',
        blue: '#9ccfd8',
        magenta: '#c4a7e7',
        cyan: '#ebbcba',
        white: '#e0def4',
        brightBlack: '#6e6a86',
        brightRed: '#eb6f92',
        brightGreen: '#31748f',
        brightYellow: '#f6c177',
        brightBlue: '#9ccfd8',
        brightMagenta: '#c4a7e7',
        brightCyan: '#ebbcba',
        brightWhite: '#e0def4',
    },

    'rose-pine-moon': {
        _label: 'Rosé Pine Moon',
        background: '#232136',
        foreground: '#e0def4',
        cursor: '#56526e',
        black: '#2a273f',
        red: '#eb6f92',
        green: '#3e8fb0',
        yellow: '#f6c177',
        blue: '#9ccfd8',
        magenta: '#c4a7e7',
        cyan: '#ea9a97',
        white: '#e0def4',
        brightBlack: '#6e6a86',
        brightRed: '#eb6f92',
        brightGreen: '#3e8fb0',
        brightYellow: '#f6c177',
        brightBlue: '#9ccfd8',
        brightMagenta: '#c4a7e7',
        brightCyan: '#ea9a97',
        brightWhite: '#e0def4',
    },

    'everforest': {
        _label: 'Everforest Dark',
        background: '#2d353b',
        foreground: '#d3c6aa',
        cursor: '#d3c6aa',
        black: '#343f44',
        red: '#e67e80',
        green: '#a7c080',
        yellow: '#dbbc7f',
        blue: '#7fbbb3',
        magenta: '#d699b6',
        cyan: '#83c092',
        white: '#d3c6aa',
        brightBlack: '#475258',
        brightRed: '#e67e80',
        brightGreen: '#a7c080',
        brightYellow: '#dbbc7f',
        brightBlue: '#7fbbb3',
        brightMagenta: '#d699b6',
        brightCyan: '#83c092',
        brightWhite: '#d3c6aa',
    },

    'kanagawa': {
        _label: 'Kanagawa',
        background: '#1f1f28',
        foreground: '#dcd7ba',
        cursor: '#c8c093',
        black: '#16161d',
        red: '#c34043',
        green: '#76946a',
        yellow: '#c0a36e',
        blue: '#7e9cd8',
        magenta: '#957fb8',
        cyan: '#6a9589',
        white: '#c8c093',
        brightBlack: '#727169',
        brightRed: '#e82424',
        brightGreen: '#98bb6c',
        brightYellow: '#e6c384',
        brightBlue: '#7fb4ca',
        brightMagenta: '#938aa9',
        brightCyan: '#7aa89f',
        brightWhite: '#dcd7ba',
    },

    'nightfox': {
        _label: 'Nightfox',
        background: '#192330',
        foreground: '#cdcecf',
        cursor: '#cdcecf',
        black: '#393b44',
        red: '#c94f6d',
        green: '#81b29a',
        yellow: '#dbc074',
        blue: '#719cd6',
        magenta: '#9d79d6',
        cyan: '#63cdcf',
        white: '#dfdfe0',
        brightBlack: '#575860',
        brightRed: '#d16983',
        brightGreen: '#8ebaa4',
        brightYellow: '#e0c989',
        brightBlue: '#86abdc',
        brightMagenta: '#baa1e2',
        brightCyan: '#7ad4d6',
        brightWhite: '#e4e4e5',
    },

    'oxocarbon': {
        _label: 'Oxocarbon',
        background: '#161616',
        foreground: '#f2f4f8',
        cursor: '#f2f4f8',
        black: '#262626',
        red: '#ff7eb6',
        green: '#42be65',
        yellow: '#ffe97b',
        blue: '#82cfff',
        magenta: '#be95ff',
        cyan: '#3ddbd9',
        white: '#dde1e6',
        brightBlack: '#393939',
        brightRed: '#ff7eb6',
        brightGreen: '#42be65',
        brightYellow: '#ffe97b',
        brightBlue: '#82cfff',
        brightMagenta: '#be95ff',
        brightCyan: '#3ddbd9',
        brightWhite: '#ffffff',
    },

    'material-ocean': {
        _label: 'Material Ocean',
        background: '#0f111a',
        foreground: '#8f93a2',
        cursor: '#84ffff',
        black: '#090b10',
        red: '#f07178',
        green: '#c3e88d',
        yellow: '#ffcb6b',
        blue: '#82aaff',
        magenta: '#c792ea',
        cyan: '#89ddff',
        white: '#eeffff',
        brightBlack: '#464b5d',
        brightRed: '#ff5370',
        brightGreen: '#c3e88d',
        brightYellow: '#ffcb6b',
        brightBlue: '#82aaff',
        brightMagenta: '#c792ea',
        brightCyan: '#89ddff',
        brightWhite: '#ffffff',
    },

    'ayu-dark': {
        _label: 'Ayu Dark',
        background: '#0a0e14',
        foreground: '#b3b1ad',
        cursor: '#e6b450',
        black: '#01060e',
        red: '#ea6c73',
        green: '#91b362',
        yellow: '#f9af4f',
        blue: '#53bdfa',
        magenta: '#fae994',
        cyan: '#90e1c6',
        white: '#c7c7c7',
        brightBlack: '#686868',
        brightRed: '#f07178',
        brightGreen: '#c2d94c',
        brightYellow: '#ffb454',
        brightBlue: '#59c2ff',
        brightMagenta: '#ffee99',
        brightCyan: '#95e6cb',
        brightWhite: '#ffffff',
    },

    'palenight': {
        _label: 'Palenight',
        background: '#292d3e',
        foreground: '#a6accd',
        cursor: '#a6accd',
        black: '#292d3e',
        red: '#f07178',
        green: '#c3e88d',
        yellow: '#ffcb6b',
        blue: '#82aaff',
        magenta: '#c792ea',
        cyan: '#89ddff',
        white: '#d0d0d0',
        brightBlack: '#434758',
        brightRed: '#ff8b92',
        brightGreen: '#ddffa7',
        brightYellow: '#ffe585',
        brightBlue: '#9cc4ff',
        brightMagenta: '#e1acff',
        brightCyan: '#a3f7ff',
        brightWhite: '#ffffff',
    },

    'cyberpunk': {
        _label: 'Cyberpunk',
        background: '#0d0d0d',
        foreground: '#00ff9c',
        cursor: '#ff00ff',
        black: '#0d0d0d',
        red: '#ff0055',
        green: '#00ff9c',
        yellow: '#ffdd00',
        blue: '#00b4ff',
        magenta: '#ff00ff',
        cyan: '#00ffff',
        white: '#cccccc',
        brightBlack: '#333333',
        brightRed: '#ff3377',
        brightGreen: '#33ffb5',
        brightYellow: '#ffee44',
        brightBlue: '#33c9ff',
        brightMagenta: '#ff55ff',
        brightCyan: '#55ffff',
        brightWhite: '#ffffff',
    },

    'synthwave': {
        _label: 'Synthwave',
        background: '#2a2139',
        foreground: '#f92aad',
        cursor: '#f92aad',
        black: '#1b1528',
        red: '#fe4450',
        green: '#72f1b8',
        yellow: '#f3e877',
        blue: '#03edf9',
        magenta: '#f92aad',
        cyan: '#03edf9',
        white: '#ffffff',
        brightBlack: '#495495',
        brightRed: '#ff6374',
        brightGreen: '#72f1b8',
        brightYellow: '#f3e877',
        brightBlue: '#03edf9',
        brightMagenta: '#f92aad',
        brightCyan: '#03edf9',
        brightWhite: '#ffffff',
    },

    'vesper': {
        _label: 'Vesper',
        background: '#101010',
        foreground: '#ffffff',
        cursor: '#ffc799',
        black: '#101010',
        red: '#f5a191',
        green: '#90b99f',
        yellow: '#e6b99d',
        blue: '#aca1cf',
        magenta: '#e29eca',
        cyan: '#ea83a5',
        white: '#a0a0a0',
        brightBlack: '#3d3d3d',
        brightRed: '#f5a191',
        brightGreen: '#90b99f',
        brightYellow: '#e6b99d',
        brightBlue: '#aca1cf',
        brightMagenta: '#e29eca',
        brightCyan: '#ea83a5',
        brightWhite: '#ffffff',
    },

    'mellow': {
        _label: 'Mellow',
        background: '#1e1e1e',
        foreground: '#c9c7cd',
        cursor: '#c9c7cd',
        black: '#1e1e1e',
        red: '#e06c75',
        green: '#57a773',
        yellow: '#d19a66',
        blue: '#61afef',
        magenta: '#c678dd',
        cyan: '#56b6c2',
        white: '#abb2bf',
        brightBlack: '#545862',
        brightRed: '#e06c75',
        brightGreen: '#98c379',
        brightYellow: '#e5c07b',
        brightBlue: '#61afef',
        brightMagenta: '#c678dd',
        brightCyan: '#56b6c2',
        brightWhite: '#c8ccd4',
    },

    'poimandres': {
        _label: 'Poimandres',
        background: '#1b1e28',
        foreground: '#a6accd',
        cursor: '#a6accd',
        black: '#1b1e28',
        red: '#d0679d',
        green: '#5de4c7',
        yellow: '#fffac2',
        blue: '#89ddff',
        magenta: '#fcc5e9',
        cyan: '#add7ff',
        white: '#ffffff',
        brightBlack: '#303340',
        brightRed: '#d0679d',
        brightGreen: '#5de4c7',
        brightYellow: '#fffac2',
        brightBlue: '#89ddff',
        brightMagenta: '#fcc5e9',
        brightCyan: '#add7ff',
        brightWhite: '#ffffff',
    },

    'midnight': {
        _label: 'Midnight',
        background: '#0e0e0e',
        foreground: '#b2b2b2',
        cursor: '#00ffcc',
        black: '#0e0e0e',
        red: '#ff5252',
        green: '#00e676',
        yellow: '#ffea00',
        blue: '#448aff',
        magenta: '#e040fb',
        cyan: '#00e5ff',
        white: '#b2b2b2',
        brightBlack: '#424242',
        brightRed: '#ff5252',
        brightGreen: '#69f0ae',
        brightYellow: '#ffff00',
        brightBlue: '#82b1ff',
        brightMagenta: '#ea80fc',
        brightCyan: '#84ffff',
        brightWhite: '#ffffff',
    },

    'horizon': {
        _label: 'Horizon',
        background: '#1c1e26',
        foreground: '#e0e0e0',
        cursor: '#e95678',
        black: '#16161c',
        red: '#e95678',
        green: '#29d398',
        yellow: '#fab795',
        blue: '#26bbd9',
        magenta: '#ee64ae',
        cyan: '#59e1e3',
        white: '#e0e0e0',
        brightBlack: '#414559',
        brightRed: '#ec6a88',
        brightGreen: '#3fdaa4',
        brightYellow: '#fbc3a7',
        brightBlue: '#3fc4de',
        brightMagenta: '#f075b5',
        brightCyan: '#6be4e6',
        brightWhite: '#e4e4e4',
    },

    'melange': {
        _label: 'Mélange',
        background: '#2a2520',
        foreground: '#ece1d7',
        cursor: '#ece1d7',
        black: '#34302c',
        red: '#b65c60',
        green: '#78997a',
        yellow: '#b5872a',
        blue: '#4f8a8b',
        magenta: '#996b76',
        cyan: '#5c8a74',
        white: '#ece1d7',
        brightBlack: '#7d7163',
        brightRed: '#c97979',
        brightGreen: '#99b59b',
        brightYellow: '#cda95e',
        brightBlue: '#76a8a9',
        brightMagenta: '#b38a97',
        brightCyan: '#7da89a',
        brightWhite: '#f4ede8',
    },
};

// ── Default theme key ──────────────────────────────────────
export const DEFAULT_THEME = 'catppuccin-mocha';

// ── Apply a theme to xterm + update CSS background ────────
export function applyTheme(term, key) {
    const t = themes[key];
    if (!t) return false;

    // strip internal _label before passing to xterm
    const { _label, ...xtermTheme } = t;
    term.options.theme = xtermTheme;

    // sync the CRT wrapper background so no colour bleed
    document.getElementById('crt').style.background = t.background;
    document.body.style.background = t.background;

    return true;
}
